export const ADD_TODO = 'ADD_TODO'

export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST'

export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

export const SUCCESS_GEN_RAND_NUM = 'SUCCESS_GEN_RAND_NUM'
export const FAIL_GEN_RAND_NUM = 'FAIL_GEN_RAND_NUM'